#!/usr/bin/perl
use warnings;
use strict;

use Time::HiRes qw(usleep nanosleep);

=duration and pitch
    http://man7.org/linux/man-pages/man4/console_codes.4.html
    ESC [ 10 ; n ]   Set bell frequency in Hz.
    ESC [ 11 ; n ]   Set bell duration in msec.
=cut

=note frequencies
56  E5           659.255
55  D#5/Eb5      622.254
54  D5           587.330
53  C#5/Db5      554.365
52  C5           523.251
51  B4           493.883
50  A#4/Bb4      466.164
49  A4 A440      440.000
48  G#4/Ab4      415.305
47  G4           391.995
46  F#4/Gb4      369.994
45  F4           349.228
44  E4           329.628
43  D#4/Eb4      311.127
42  D4           293.665
41  C#4/Db4      277.183
40  C4 Middle C  261.626
=cut

# Notes
my $notes = {
    c4 => 262,
    C4 => 277,
    d4 => 294,
    e4 => 330,
    f4 => 349,
    F4 => 370,
    g4 => 392,
    a4 => 440,
    b4 => 494,
    c5 => 523,
    d5 => 587,
    e5 => 659,
};

# Duration
my $dur = {
    sq => 100,
    qu => 200,
    qd => 300,
    cr => 400,
    cd => 600,
    mi => 800,
};

sub play($$) {
    my ($freq, $dur) = (shift, shift);
    # ESC [ 10 ; n ]   Set bell frequency in Hz.
    # ESC [ 11 ; n ]   Set bell duration in msec.
    printf("\e[10;%d]\e[11;%d]\a\e[1;1H\n", $freq, $dur);
    rest ($dur);
    return 0;
}

sub rest($) {

    my $dur = shift;

    # 1 millisecond == 1000 microseconds
    usleep($dur*1000);
    return 0;

}

my $file = shift;
die "Usage: $0 MUSIC_FILE\n" if ! $file;

printf "\ec\e]R";

open (my $file_fh, "$file") || die "Can't read '$file': $!\n";
while (defined (my $line = <$file_fh>)) {

    #
    next if $line =~ /^\s*$/;
    if ( $line =~ /(\w+),\s*(\w+)/ ) {
        if ( $1 eq 'rest' ) {
            rest $dur->{$2};
        } else {
            play $notes->{$1}, $dur->{$2};
        }
    } elsif ( $line =~ /^# (.*)$/) {
        printf "\e[H\e[J$1\n";
    } else {
        chomp $line;
        die "Nasty line: [$line]\n";
    }

}
close $file_fh;

printf "\ec\e]R"

